server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/logintest
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: dailycodeworks@gmail.com
    password: yr_email_pass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
